on:
  #schedule:
    #- cron: '30 20,13 * * 1,2,4,5,6,7

jobs:
  test_schedule:
    runs-on: ubuntu-latest
    steps:
      - name: All the days f
        run: cd src && ./auto.py --run_all n --selected_app 1
