name: Python Web Apps Flask Running

on: push

jobs:
  my-job:
    name: Using Flask
    runs-on: ubuntu-latest
    steps:
      - name: Running Tango App
        run: ls /home/runner/work/pauer-price/#cd /home/runner/work/pauer-price/pauer-price/src && ./auto.py --run_all n --selected_app 1

        
